name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: My Build
        shell: cmd
        working-directory: ${{github.workspace}}/src/odbc/rsodbc
        run: |
          dir "C:\Program Files\Microsoft Visual Studioo\2022"
          dir "C:\Program Files\Microsoft Visual Studioo\2022\Community"
          dir "C:\Program Files\Microsoft Visual Studioo\2022\Community\VC"
          dir "C:\Program Files\Microsoft Visual Studioo\2022\Community\VC\Auxiliary"
          dir "C:\Program Files\Microsoft Visual Studioo\2022\Community\VC\Auxiliary\Build"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat"
          ./package64.bat 2.0.0 13
