name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: My Build
        shell: cmd
        working-directory: ${{github.workspace}}/src/odbc/rsodbc
        run: ./package64.bat 2.0.0 13
