name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]  # or [x86] for 32-bit
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install WiX
        run: dotnet tool install --global wix

      # - name: Build WiX on Windows
      #   run: wix build .\nexus.wxs

      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Build ODBC
        shell: cmd
        working-directory: ${{github.workspace}}/src/odbc/rsodbc
        run: |
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
          ./package64.bat 2.0.0 13
